jellyseerr:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - PUID=1000
            - PGID=1000
            - LOG_LEVEL=debug
            - TZ=Asia/Calcutta
       ports:
            - 5055:5055
       volumes:
            - ./volumes/overseerr/config:/config
       restart: unless-stopped